### ISSUE TITLE
LLL support?

### ISSUE THREAD

**Issue by HightOracle** [Spookybuddy/LethalMods#1]
Hello, I liked this moon and I just wanted to ask if it will be transfered to Lethal Level Loader in the future (or maybe LLL mirror version will be made)

**Comment by Spookybuddy** [comment]
I will gladly begin development of a Lethal Level Loader version of the maps, but that will take some time. They will be posted as their own mods, as they have conflicting dependencies, but will be exact copies of the environment.

**Comment by Spookybuddy** [comment]
@HightOracle You can download the .lethalbundle files from the new repository: https://github.com/Spookybuddy/LethalLoaderMods

While still a WIP, they are almost finished and will have a Thunderstore page made soon. Just need to fix a few bugs, especially with the new v50 elements.

I'll update you again once the Thunderstore page has been made, but just providing confirmation that I am still keeping my promise to make LethalLevelLoader versions.

**Comment by HightOracle** [comment]
Thanks you for your work

вс, 5 мая 2024 г., 12:11 Spookybuddy ***@***.***>:

**Comment by Spookybuddy** [comment]
@HightOracle The maps have been uploaded to the Thunderstore. Since Lethal Expansion is no longer in use I have opted to overwrite them with the Level Loader versions. Find them here: https://thunderstore.io/c/lethal-company/p/SpookyBuddy/

**Comment by HightOracle** [comment]
Thank you for your work ☺️

чт, 16 мая 2024 г., 07:26 Spookybuddy ***@***.***>:
